Assignment: StudentRegistry & OwnAble tests
BlockheaderWeb3-Community/cairo-bootcamp-3 pull request #28
Opened 2024-10-14 06:58 UTC by RichoKD

2024-10-14 10:58 UTC, ibsule requested changes
Can you please sync with the latest changes in the `main` so the CI can be run on your PR?

2024-10-15 06:13 UTC, princeibs requested changes
Please let me know if you need more clarity on the reviews

2024-10-15 06:13 UTC, princeibs commented on tests/test_student_registry.cairo
> +    student_registry_dispatcher.add_student('Jane', account2, 21, 101, true);
After adding the student, can you add assertion statements similar to the image below that verifies the student was added successfully?
<img width="671" alt="image" src="https://github.com/user-attachments/assets/5fd248c3-33ed-451c-9bef-4d41ab106a88">

2024-10-15 06:13 UTC, princeibs commented on tests/test_student_registry.cairo
> +    assert(student1 == true, 'Student updated failed');
Can you use the updated properties of the student e.g `name` to verify the student details was updated successfully?

2024-10-15 06:13 UTC, princeibs commented on tests/test_student_registry.cairo
> +    assert(student1 == true, 'Student deleted failed');
Please add assertions to verify the student was deleted successfully

2024-10-22 20:16 UTC, closed without merging